esphome:
  name: geyserwise-tse-a8259b
  friendly_name: Geyserwise TSE Office
  name_add_mac_suffix: false

wifi:
  ssid: "Bay Solar"
  password: "0224950016"

mqtt:
  broker: 10.10.0.3
  port: 1883
  username: mqtt-user
  password: mqtt-pass
  discovery: false
  birth_message:
  will_message:

# Enable ESPHome dashboard logging
api:
  encryption:
    key: !secret api_key

logger:
  level: DEBUG
  baud_rate: 0

time:
  - platform: sntp
    id: my_time

uart:
  rx_pin: GPIO13
  tx_pin: GPIO15
  baud_rate: 9600

tuya:
  id: gw_tuya

# TUYA DEBUG - find unknown datapoints
tuya:
  id: gw_tuya
  on_datapoint:
    then:
      - lambda: |-
          ESP_LOGD("tuya.unknown", "Datapoint ID %d value %d", x.id, x.value.uint_value);

sensor:
  - platform: tuya
    name: "Water Temperature"
    sensor_datapoint: 10

  - platform: tuya
    name: "Element Status"
    sensor_datapoint: 13

  - platform: tuya
    name: "Error Code"
    sensor_datapoint: 20

  - platform: wifi_signal
    name: "WiFi Signal Percent"
    update_interval: 60s

text_sensor:
  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: Connected SSID
    bssid:
      name: Connected BSSID

switch:
  - platform: tuya
    name: "Power"
    switch_datapoint: 1

select:
  - platform: tuya
    name: "Mode"
    enum_datapoint: 2
    options:
      0: "Standby"
      1: "Normal"
      2: "Timer"
      3: "Setpoint"

number:
  - platform: tuya
    name: "PTC Element Temp"
    number_datapoint: 102
    min_value: 30
    max_value: 75
    step: 1

  - platform: tuya
    name: "Block 1 00:00-06:00"
    number_datapoint: 103
    min_value: 30
    max_value: 75
    step: 1

  - platform: tuya
    name: "Block 2 06:00-12:00"
    number_datapoint: 104
    min_value: 30
    max_value: 75
    step: 1

  - platform: tuya
    name: "Block 3 12:00-18:00"
    number_datapoint: 105
    min_value: 30
    max_value: 75
    step: 1

  - platform: tuya
    name: "Block 4 18:00-00:00"
    number_datapoint: 106
    min_value: 30
    max_value: 75
    step: 1
